import pandas as pd
import datetime
import os

def generate_report():
    print("📊 Generating Mission Report...")
    
    log_file = "telemetry_log.csv"
    if not os.path.exists(log_file):
        print(f"❌ Error: {log_file} not found.")
        return

    try:
        df = pd.read_csv(log_file)
        if df.empty:
            print("⚠️ Warning: Log file is empty.")
            return
            
        # Calculate Metrics
        max_alt = df['altitude'].max()
        max_vel = df['velocity'].max()
        flight_duration = df['timestamp'].iloc[-1] - df['timestamp'].iloc[0]
        
        # Descent Rate (Average negative velocity during descent)
        descent_phase = df[df['status'] == 'DESCENT']
        avg_descent_rate = descent_phase['velocity'].mean() if not descent_phase.empty else 0.0

        # Landing Coordinates
        last_row = df.iloc[-1]
        landing_lat = last_row.get('gps_lat', 'N/A')
        landing_lon = last_row.get('gps_long', 'N/A')
        
        # Generate Markdown Content
        report_content = f"""# 🚀 Teknofest 2026 - Flight Mission Report

**Date:** {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Team:** KTU Rocket Team
**Competition Category:** High Altitude

---

## 🏆 Key Performance Indicators (KPIs)

| Metric | Value | Unit |
| :--- | :--- | :--- |
| **Apogee (Max Altitude)** | `{max_alt:.2f}` | meters |
| **Top Speed** | `{max_vel:.2f}` | m/s |
| **Flight Duration** | `{flight_duration:.2f}` | seconds |
| **Avg. Descent Rate** | `{avg_descent_rate:.2f}` | m/s |

---

## 📍 Recovery Coordinates
**Latitude:** `{landing_lat}`
**Longitude:** `{landing_lon}`

[Open in Google Maps](https://www.google.com/maps/search/?api=1&query={landing_lat},{landing_lon})

---

## 📉 Flight Status Summary
- **Lift-off Time:** T+{df['timestamp'].iloc[0]:.2f}s
- **Apogee Time:** T+{df.loc[df['altitude'].idxmax(), 'timestamp']:.2f}s
- **Landing Time:** T+{df['timestamp'].iloc[-1]:.2f}s

*Report automatically generated by Teknofest Mission Control System.*
"""

        with open("FLIGHT_REPORT.md", "w", encoding="utf-8") as f:
            f.write(report_content)
            
        print("✅ Success: FLIGHT_REPORT.md generated.")

    except Exception as e:
        print(f"❌ Error generating report: {e}")

if __name__ == "__main__":
    generate_report()
